version: "3.7"

services:
  php-cli:
    build:
      context: ./.docker/php
      dockerfile: php-cli.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    env_file:
      - .env
      - ./.docker/environment.env
    tty: true

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
      - ./.docker/environment.env
    restart: on-failure
